[default]
extend-ignore-re = [
    '`[^`\n]+`',  # skip inline code
    '```[\s\S]*?```',  # skip code blocks
    'Bún bò Nam Bô',  # otherwise "Nam" is considered as a typo of "Name"
]

[default.extend-words]
SER = "SER"

[files]
extend-exclude = ['sources/api/*.mdx']
