title: KeyValueStoreStats
required:
  - readCount
  - writeCount
  - deleteCount
  - listCount
type: object
properties:
  readCount:
    type: integer
    example: 9
  writeCount:
    type: integer
    example: 3
  deleteCount:
    type: integer
    example: 6
  listCount:
    type: integer
    example: 2
  s3StorageBytes:
    type: integer
    example: 18
