title: KeyValueStoreStats
required:
  - readCount
  - writeCount
  - deleteCount
  - listCount
type: object
properties:
  readCount:
    type: integer
    examples: [9]
  writeCount:
    type: integer
    examples: [3]
  deleteCount:
    type: integer
    examples: [6]
  listCount:
    type: integer
    examples: [2]
  s3StorageBytes:
    type: integer
    examples: [18]
