title: KeyValueStore
required:
  - id
  - name
  - createdAt
  - modifiedAt
  - accessedAt
  - consoleUrl
  - keysPublicUrl
type: object
properties:
  id:
    type: string
    example: WkzbQMuFYuamGv3YF
  name:
    type: string
    example: d7b9MDYsbtX5L7XAj
  userId:
    type: string
    nullable: true
    example: BPWDBd7Z9c746JAnF
  username:
    type: string
    nullable: true
    example: janedoe
  createdAt:
    type: string
    example: '2019-12-12T07:34:14.202Z'
  modifiedAt:
    type: string
    example: '2019-12-13T08:36:13.202Z'
  accessedAt:
    type: string
    example: '2019-12-14T08:36:13.202Z'
  actId:
    type: string
    nullable: true
    example: null
  actRunId:
    type: string
    nullable: true
    example: null
  consoleUrl:
    type: string
    example: 'https://console.apify.com/storage/key-value-stores/27TmTznX9YPeAYhkC'  
  keysPublicUrl:
    type: string
    description: "A public link to access keys of the key-value store directly."
    example: 'https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/keys?signature=abc123'
  urlSigningSecretKey:
    type: string
    description: "A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the key-value store."
    nullable: true
  generalAccess:
    type: string
    enum:
      - RESTRICTED
      - ANYONE_WITH_ID_CAN_READ
      - FOLLOW_USER_SETTING
    example: RESTRICTED
  stats:
    $ref: ./KeyValueStoreStats.yaml
