title: KeyValueStore
required:
  - id
  - createdAt
  - modifiedAt
  - accessedAt
  - consoleUrl
  - keysPublicUrl
type: object
properties:
  id:
    type: string
    examples: [WkzbQMuFYuamGv3YF]
  name:
    type: string
    examples: [d7b9MDYsbtX5L7XAj]
  userId:
    type: [string, "null"]
    examples: [BPWDBd7Z9c746JAnF]
  username:
    type: [string, "null"]
    examples: [janedoe]
  createdAt:
    type: string
    format: date-time
    examples: ["2019-12-12T07:34:14.202Z"]
  modifiedAt:
    type: string
    format: date-time
    examples: ["2019-12-13T08:36:13.202Z"]
  accessedAt:
    type: string
    format: date-time
    examples: ["2019-12-14T08:36:13.202Z"]
  actId:
    type: [string, "null"]
    examples: [null]
  actRunId:
    type: [string, "null"]
    examples: [null]
  consoleUrl:
    type: string
    format: uri
    examples: ["https://console.apify.com/storage/key-value-stores/27TmTznX9YPeAYhkC"]
  keysPublicUrl:
    type: string
    format: uri
    description: A public link to access keys of the key-value store directly.
    examples: [https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/keys?signature=abc123]
  urlSigningSecretKey:
    type: [string, "null"]
    description: A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the key-value store.
  generalAccess:
    $ref: ../common/GeneralAccessEnum.yaml
  stats:
    $ref: ./KeyValueStoreStats.yaml
